2017-05-03 23:43:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_OPTION" not found; SQL statement:
CREATE TABLE `sys_distribution` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `distributer` varchar(255) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `customer_id` int(11) NOT NULL,
  `disIntegerId` int(11) DEFAULT NULL,
  `createTime` date DEFAULT NULL,
  `distributionTime` date DEFAULT NULL,
  `nextDistributionTime` date DEFAULT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `distributerId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_d65xrh8bvb8039bmqudyg0ddu` (`customer_id`),
  KEY `FK_y64tinolia957w8v1djjw0yp` (`STATUS_ID`),
  CONSTRAINT `FK_d65xrh8bvb8039bmqudyg0ddu` FOREIGN KEY (`customer_id`) REFERENCES `sys_customer` (`id`),
  CONSTRAINT `FK_y64tinolia957w8v1djjw0yp` FOREIGN KEY (`STATUS_ID`) REFERENCES `sys_option` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 [42102-195]
2017-05-03 23:43:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_DISTRIBUTION" not found; SQL statement:
INSERT INTO `sys_distribution` VALUES ('18', null, null, '一定要及时配送!', '2', null, null, '2016-10-29', '2016-11-05', '92', null), ('21', null, null, '！！！', '2', null, '2016-10-27', '2016-10-30', '2016-11-10', '106', null), ('22', null, null, '信息', '3', null, '2016-10-28', '2016-10-28', '2016-10-30', '92', null) [42102-195]
2017-05-03 23:43:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_FEED" not found; SQL statement:
CREATE TABLE `sys_distribution_item` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `DISTRIBUTION_ID` int(11) DEFAULT NULL,
  `FEED_ID` int(11) DEFAULT NULL,
  `amount` int(11) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_n2a54rluoho4bqukkyhro8ece` (`DISTRIBUTION_ID`),
  KEY `FK_b0dkpigbwia45wm98o7xk6eve` (`FEED_ID`),
  CONSTRAINT `FK_b0dkpigbwia45wm98o7xk6eve` FOREIGN KEY (`FEED_ID`) REFERENCES `sys_feed` (`id`),
  CONSTRAINT `FK_n2a54rluoho4bqukkyhro8ece` FOREIGN KEY (`DISTRIBUTION_ID`) REFERENCES `sys_distribution` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8 [42102-195]
2017-05-03 23:43:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_DISTRIBUTION_ITEM" not found; SQL statement:
INSERT INTO `sys_distribution_item` VALUES ('24', '18', '1', '9', '891.00'), ('25', '18', '2', '9', '792.00'), ('26', '21', '1', '8', '792.00'), ('27', '21', '2', '8', '704.00'), ('28', '22', '1', '7', '693.00') [42102-195]
2017-05-03 23:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_USER" not found; SQL statement:
CREATE TABLE `sys_notify` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content_` varchar(5000) DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  `isReaded` int(1) DEFAULT NULL,
  `poster` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `receiver_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_gja9q811npq0tdl13p76cgbyh` (`receiver_id`),
  CONSTRAINT `FK_gja9q811npq0tdl13p76cgbyh` FOREIGN KEY (`receiver_id`) REFERENCES `sys_user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 [42102-195]
2017-05-03 23:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_NOTIFY" not found; SQL statement:
INSERT INTO `sys_notify` VALUES ('1', '测试消息正文', '2017-03-10 18:09:41', '0', '系统', '测试消息', '1') [42102-195]
2017-05-03 23:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Constraint "UK_E2AK9XJFULRCNDL8OP0IU9PBD" already exists; SQL statement:
CREATE TABLE `sys_org_sequence` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cursor_` int(11) DEFAULT NULL,
  `lastTime` datetime DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_e2ak9xjfulrcndl8op0iu9pbd` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [90045-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:109)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:77)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:178)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
2017-05-03 23:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Constraint "NAME" already exists; SQL statement:
CREATE TABLE `sys_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `canInherit` int(1) DEFAULT NULL,
  `isBuiltIn` int(1) DEFAULT NULL,
  `region` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 [90045-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:109)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:77)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:178)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
2017-05-03 23:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_ROLE" not found; SQL statement:
INSERT INTO `sys_role` VALUES ('1', '超级管理员角色应用系统的所有菜单功能和功能操作的权限，系统中权利最大的角色。', '超级管理员', '0', '1', '*'), ('2', '地市管理员具备一定的权限；可以分配权限、管理地市用户等.', '地市管理员', '1', '0', '10'), ('5', '普通用户仅具备基础查看功能.', '普通用户', '0', '0', '20') [42102-195]
2017-05-03 23:43:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_ROLE" not found; SQL statement:
CREATE TABLE `sys_role_resource` (
  `role_id` int(11) NOT NULL,
  `res_id` int(11) NOT NULL,
  PRIMARY KEY (`role_id`,`res_id`),
  KEY `FKB804BFC5961BF2AB` (`res_id`),
  KEY `FKB804BFC5107108FD` (`role_id`),
  CONSTRAINT `FK_10rpk2k4gddcfy7bnnmqgap3s` FOREIGN KEY (`role_id`) REFERENCES `sys_role` (`id`),
  CONSTRAINT `FK_c3ydxo7wsn53sfygbu1t1ages` FOREIGN KEY (`res_id`) REFERENCES `sys_resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [42102-195]
2017-05-03 23:43:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_ROLE_RESOURCE" not found; SQL statement:
INSERT INTO `sys_role_resource` VALUES ('1', '1'), ('2', '1'), ('5', '1'), ('1', '2'), ('2', '2'), ('5', '2'), ('1', '7'), ('2', '7'), ('5', '7'), ('1', '9'), ('2', '9'), ('5', '9'), ('1', '10'), ('2', '10'), ('5', '10'), ('1', '12'), ('2', '12'), ('5', '12'), ('1', '13'), ('2', '13'), ('5', '13'), ('1', '15'), ('5', '15'), ('1', '16'), ('1', '22'), ('1', '24'), ('1', '25'), ('1', '26'), ('1', '27'), ('1', '28'), ('1', '29'), ('5', '29'), ('1', '30'), ('2', '30'), ('1', '31'), ('2', '31'), ('1', '32'), ('2', '32'), ('1', '33'), ('2', '33'), ('5', '33'), ('1', '35'), ('2', '35'), ('5', '35'), ('1', '36'), ('2', '36'), ('5', '36'), ('1', '37'), ('2', '37'), ('5', '37'), ('1', '38'), ('2', '38'), ('5', '38'), ('1', '39'), ('2', '39'), ('1', '40'), ('2', '40'), ('1', '41'), ('2', '41'), ('1', '42'), ('2', '42'), ('5', '42'), ('1', '43'), ('2', '43'), ('1', '44'), ('2', '44'), ('1', '45'), ('2', '45'), ('1', '46'), ('2', '46'), ('5', '46'), ('1', '47'), ('1', '60'), ('2', '60'), ('1', '68'), ('2', '68'), ('5', '68'), ('1', '69'), ('2', '69'), ('1', '70'), ('2', '70'), ('1', '71'), ('2', '71'), ('1', '72'), ('2', '72'), ('5', '72'), ('1', '74'), ('5', '74'), ('1', '75'), ('1', '76'), ('1', '77'), ('1', '78'), ('5', '78'), ('1', '104'), ('2', '104'), ('1', '105'), ('2', '105'), ('1', '106'), ('2', '106'), ('1', '107'), ('2', '107'), ('1', '108'), ('2', '108'), ('1', '114'), ('2', '114'), ('5', '114'), ('1', '115'), ('2', '115'), ('5', '115'), ('1', '116'), ('2', '116'), ('5', '116'), ('1', '117'), ('2', '117'), ('5', '117'), ('1', '118'), ('2', '118'), ('5', '118'), ('1', '120'), ('1', '121'), ('5', '121'), ('1', '122'), ('1', '123'), ('5', '123'), ('1', '124'), ('1', '125'), ('5', '125'), ('1', '126'), ('5', '126'), ('1', '129'), ('1', '130'), ('2', '130'), ('5', '130'), ('1', '131'), ('1', '135'), ('1', '136'), ('1', '137'), ('1', '138'), ('1', '139'), ('1', '140'), ('1', '141'), ('1', '142'), ('1', '143'), ('1', '144'), ('1', '145'), ('1', '146'), ('1', '147'), ('1', '148'), ('1', '149'), ('1', '150'), ('1', '151'), ('1', '152'), ('5', '152'), ('1', '153'), ('1', '154'), ('1', '155'), ('5', '155'), ('1', '156'), ('1', '157'), ('1', '158'), ('1', '160'), ('1', '161'), ('1', '165'), ('1', '169'), ('1', '171'), ('1', '172'), ('1', '173'), ('1', '174'), ('1', '175') [42102-195]
2017-05-03 23:43:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_USER" not found; SQL statement:
CREATE TABLE `sys_task` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `createTime` date DEFAULT NULL,
  `filePath` varchar(255) DEFAULT NULL,
  `finishTime` date DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `sql_` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `templatePath` varchar(255) DEFAULT NULL,
  `totalRecords` int(11) DEFAULT NULL,
  `author_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_1dvnu1k5159loj18bu5tpjga0` (`author_id`),
  CONSTRAINT `FK_1dvnu1k5159loj18bu5tpjga0` FOREIGN KEY (`author_id`) REFERENCES `sys_user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 [42102-195]
2017-05-03 23:43:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_TASK" not found; SQL statement:
INSERT INTO `sys_task` VALUES ('1', '2017-01-23', '/Users/huzd/Applications/apache-tomcat-8.0.37/exportDir/3f20b89a-efba-4cd6-b340-33f3ef9e4ec3.xls', '2017-02-06', '准则差异调整报表（财务侧）_超级管理员_20170123', null, 'select *  from MD_STD_DIF_ADJT_FNC_M', 'F', '1.xls', '32', '1'), ('2', '2017-02-06', '/Users/huzd/Applications/apache-tomcat-8.0.37/exportDir/03fc7626-7530-4008-b2d3-c6d0018a2480.xls', '2017-02-06', '准则差异调整报表（财务侧）_超级管理员_20170206', null, 'select *  from MD_STD_DIF_ADJT_FNC_M', 'F', '1.xls', '32', '1'), ('3', '2017-02-07', '/Users/huzd/Applications/apache-tomcat-8.0.37/exportDir/0f8474cc-5ed5-4bc1-a2df-98b8f09579e6.xls', '2017-02-07', '准则差异调整报表（财务侧）_超级管理员_20170207', null, 'select *  from MD_STD_DIF_ADJT_FNC_M', 'F', '1.xls', '32', '1'), ('4', '2017-02-07', '/Users/huzd/Applications/apache-tomcat-8.0.37/exportDir/16d1b850-c39e-4cfd-8ef8-091ee7ebb59d.xls', '2017-02-07', '准则差异调整报表（财务侧）_超级管理员_20170207', null, 'select *  from MD_STD_DIF_ADJT_FNC_M', 'F', '1.xls', '32', '1'), ('5', '2017-03-06', null, '2017-03-16', '准则差异调整报表（财务侧）_超级管理员_20170306', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('6', '2017-03-06', null, '2017-03-06', '准则差异调整报表（财务侧）__20170306', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('7', '2017-03-06', null, '2017-03-06', '准则差异调整报表（财务侧）__20170306', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('8', '2017-03-13', null, '2017-03-13', '准则差异调整报表（财务侧）_超级管理员_20170313', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('9', '2017-03-13', null, '2017-03-16', '未履约义务清单 - 新增营销案明细_超级管理员_20170313', '任务参数异常！', '', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/6.xls', null, '1'), ('10', '2017-03-13', null, '2017-03-13', '未履约义务清单 - 新增营销案明细_超级管理员_20170313', '任务参数异常！', '', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/6.xls', null, '1'), ('11', '2017-03-13', null, '2017-03-13', '未履约义务清单 - 新增营销案明细_超级管理员_20170313', '任务参数异常！', '', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/6.xls', null, '1'), ('12', '2017-03-13', null, '2017-03-13', '未履约义务清单 - 新增营销案明细_超级管理员_20170313', '任务参数异常！', '', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/6.xls', null, '1'), ('13', '2017-03-28', null, '2017-03-28', '酬金报表_超级管理员_20170328', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,REM_NAME,BUSN_NAME,SUBJ_NAME,PRPT_DATE,MON_NEW_OCR_REV,MON_NEW_PRPT_REV,SMON_TOT_UN_PRPT_BAL,SMON_TOT_PRPT_REV,EMON_TOT_UN_PRPT_BAL from AP_REM_PRPT_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/7.xls', null, '1'), ('14', '2017-03-28', null, '2017-03-28', '酬金报表_超级管理员_20170328', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,REM_NAME,BUSN_NAME,SUBJ_NAME,PRPT_DATE,MON_NEW_OCR_REV,MON_NEW_PRPT_REV,SMON_TOT_UN_PRPT_BAL,SMON_TOT_PRPT_REV,EMON_TOT_UN_PRPT_BAL from AP_REM_PRPT_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/7.xls', null, '1'), ('15', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）- 明细_测试小号_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,CNTRT_ID,SERV_NUM,MARKET_CDE,MARKET_NAME,SUBJ_NAME,SUBJ_FEE from AP_STD_DIF_ADJT_OPER_DTL_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/2.xls', null, '56'), ('16', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）- 汇总_测试小号_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,SUBJ_FEE,SUBJ_TOT from AP_STD_DIF_ADJT_OPER_COLLECT_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/20170323145320959_tXcHhd.xls', null, '56'), ('17', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_测试小号_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '56'), ('18', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('19', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('20', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('21', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('22', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1'), ('23', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）- 明细_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,CNTRT_ID,SERV_NUM,MARKET_CDE,MARKET_NAME,SUBJ_NAME,SUBJ_FEE from AP_STD_DIF_ADJT_OPER_DTL_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/2.xls', null, '1'), ('24', '2017-04-14', null, '2017-04-14', '准则差异调整报表（财务侧）_超级管理员_20170414', '数据库查询异常', 'select  DEAL_DATE,REGION_NAME,SUBJ_NAME,TAX_RATE,PRC_TAX_TOT,TAX_NUM,NO_TAX_REV from AP_STD_DIF_ADJT_FNC_M', 'E', '/Users/huzd/Applications/apache-tomcat-8.0.37/REPORT_TEMPLATE/1.xls', null, '1') [42102-195]
2017-05-03 23:43:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_ROLE" not found; SQL statement:
CREATE TABLE `sys_user_role` (
  `user_id` int(11) NOT NULL,
  `role_id` int(11) NOT NULL,
  KEY `FK_fxu3td9m5o7qov1kbdvmn0g0x` (`role_id`),
  KEY `FK_fethvr269t6stivlddbo5pxry` (`user_id`),
  CONSTRAINT `FK_fethvr269t6stivlddbo5pxry` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`),
  CONSTRAINT `FK_fxu3td9m5o7qov1kbdvmn0g0x` FOREIGN KEY (`role_id`) REFERENCES `sys_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 [42102-195]
2017-05-03 23:43:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_USER_ROLE" not found; SQL statement:
INSERT INTO `sys_user_role` VALUES ('1', '1'), ('1', '2'), ('1', '5'), ('55', '2'), ('55', '5'), ('56', '2'), ('56', '5') [42102-195]
2017-05-03 23:47:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Constraint "NAME" already exists; SQL statement:
CREATE TABLE `sys_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `canInherit` int(1) DEFAULT NULL,
  `isBuiltIn` int(1) DEFAULT NULL,
  `region` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 [90045-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:109)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:77)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:178)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
2017-05-03 23:47:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_ROLE" not found; SQL statement:
INSERT INTO `sys_role` VALUES ('1', '超级管理员角色应用系统的所有菜单功能和功能操作的权限，系统中权利最大的角色。', '超级管理员', '0', '1', '*'), ('2', '地市管理员具备一定的权限；可以分配权限、管理地市用户等.', '地市管理员', '1', '0', '10'), ('5', '普通用户仅具备基础查看功能.', '普通用户', '0', '0', '20') [42102-195]
2017-05-03 23:48:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Constraint "NAME" already exists; SQL statement:
CREATE TABLE `sys_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `canInherit` int(1) DEFAULT NULL,
  `isBuiltIn` int(1) DEFAULT NULL,
  `region` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY name (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 [90045-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:109)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:77)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:178)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:193)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
2017-05-03 23:48:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "SYS_ROLE" not found; SQL statement:
INSERT INTO `sys_role` VALUES ('1', '超级管理员角色应用系统的所有菜单功能和功能操作的权限，系统中权利最大的角色。', '超级管理员', '0', '1', '*'), ('2', '地市管理员具备一定的权限；可以分配权限、管理地市用户等.', '地市管理员', '1', '0', '10'), ('5', '普通用户仅具备基础查看功能.', '普通用户', '0', '0', '20') [42102-195]
